name: Build and Publish Devs only

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - syntaxex/**
      - language-configuration.json
      - tsconfig.json
      - webpack.config.json
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['19']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Build and Package
        run: npm run package-extension -- -o kotlin.vsix
      - name: short-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          variable_name: SHA_SHORT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-kotlin-${{ env.SHA_SHORT }}
          path: ./kotlin.vsix


